//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Transactions')
export class TransactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  transactionID: string;

  @Column('integer', { nullable: true })
  customerID: number;

  @Column('integer', { nullable: true })
  serviceID: number;

  @Column('real', { nullable: true })
  amount: number;

  @Column('date', { nullable: true })
  date: Date;

  @Column('text', { nullable: true })
  status: string;
}
